<?php
/**
 * ResultDeliveryTime
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SIW API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ResultDeliveryTime Class Doc Comment
 *
 * @category Class
 * @description Listing of Delivery Time Components produced by the Ingrid Delivery Checkout.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ResultDeliveryTime implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ResultDeliveryTime';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'carrier_delivery_promise' => '\OpenAPI\Client\Model\ResultDeliveryTimeRange',
        'customer_delivery_promise' => '\OpenAPI\Client\Model\ResultDeliveryTimeRange',
        'pickup_from_merchant' => '\OpenAPI\Client\Model\ResultDeliveryTimeRange'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'carrier_delivery_promise' => null,
        'customer_delivery_promise' => null,
        'pickup_from_merchant' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'carrier_delivery_promise' => false,
		'customer_delivery_promise' => false,
		'pickup_from_merchant' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'carrier_delivery_promise' => 'carrier_delivery_promise',
        'customer_delivery_promise' => 'customer_delivery_promise',
        'pickup_from_merchant' => 'pickup_from_merchant'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'carrier_delivery_promise' => 'setCarrierDeliveryPromise',
        'customer_delivery_promise' => 'setCustomerDeliveryPromise',
        'pickup_from_merchant' => 'setPickupFromMerchant'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'carrier_delivery_promise' => 'getCarrierDeliveryPromise',
        'customer_delivery_promise' => 'getCustomerDeliveryPromise',
        'pickup_from_merchant' => 'getPickupFromMerchant'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('carrier_delivery_promise', $data ?? [], null);
        $this->setIfExists('customer_delivery_promise', $data ?? [], null);
        $this->setIfExists('pickup_from_merchant', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets carrier_delivery_promise
     *
     * @return \OpenAPI\Client\Model\ResultDeliveryTimeRange|null
     */
    public function getCarrierDeliveryPromise()
    {
        return $this->container['carrier_delivery_promise'];
    }

    /**
     * Sets carrier_delivery_promise
     *
     * @param \OpenAPI\Client\Model\ResultDeliveryTimeRange|null $carrier_delivery_promise carrier_delivery_promise
     *
     * @return self
     */
    public function setCarrierDeliveryPromise($carrier_delivery_promise)
    {

        if (is_null($carrier_delivery_promise)) {
            throw new \InvalidArgumentException('non-nullable carrier_delivery_promise cannot be null');
        }

        $this->container['carrier_delivery_promise'] = $carrier_delivery_promise;

        return $this;
    }

    /**
     * Gets customer_delivery_promise
     *
     * @return \OpenAPI\Client\Model\ResultDeliveryTimeRange|null
     */
    public function getCustomerDeliveryPromise()
    {
        return $this->container['customer_delivery_promise'];
    }

    /**
     * Sets customer_delivery_promise
     *
     * @param \OpenAPI\Client\Model\ResultDeliveryTimeRange|null $customer_delivery_promise customer_delivery_promise
     *
     * @return self
     */
    public function setCustomerDeliveryPromise($customer_delivery_promise)
    {

        if (is_null($customer_delivery_promise)) {
            throw new \InvalidArgumentException('non-nullable customer_delivery_promise cannot be null');
        }

        $this->container['customer_delivery_promise'] = $customer_delivery_promise;

        return $this;
    }

    /**
     * Gets pickup_from_merchant
     *
     * @return \OpenAPI\Client\Model\ResultDeliveryTimeRange|null
     */
    public function getPickupFromMerchant()
    {
        return $this->container['pickup_from_merchant'];
    }

    /**
     * Sets pickup_from_merchant
     *
     * @param \OpenAPI\Client\Model\ResultDeliveryTimeRange|null $pickup_from_merchant pickup_from_merchant
     *
     * @return self
     */
    public function setPickupFromMerchant($pickup_from_merchant)
    {

        if (is_null($pickup_from_merchant)) {
            throw new \InvalidArgumentException('non-nullable pickup_from_merchant cannot be null');
        }

        $this->container['pickup_from_merchant'] = $pickup_from_merchant;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


