<?php
/**
 * PickupLocationTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SIW API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PickupLocationTypeTest Class Doc Comment
 *
 * @category    Class
 * @description - UNKNOWN_PICKUP_LOCATION_TYPE: Location type is now known for some reason  - LOCKER: Locker location type. Example Instabox or a DHL locker  - STORE: Can be a merchant&#39;s store or any other store that handles logistics  - POSTOFFICE: Postal office  - MANNED: A manned service point
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PickupLocationTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PickupLocationType"
     */
    public function testPickupLocationType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
